# Test 2024-05-04 at 23:26:17

name: Test

run-name: 2024-05-04 at 23:26:17

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - name: Cpan
      run:  sudo cpan install -T Data::Dump  Digest::SHA1

    - name: Upload images
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "AAAA" > aaa.txt
        perl -Idtt/lib -Igh/lib -M"GitHub::Crud" -e"GitHub::Crud::writeBinaryFileFromFileInCurrentRun('aaa.txt', 'aaa.txt')"
