# Test 2024-05-05 at 01:12:54

name: Test

run-name: 2024-05-05 at 01:12:54

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        perl -e"use v5.34; for(1..9999999) {say}" > aaa.txt
        zip aaa aaa.txt
        ls -lah *
        git config user.name "aaa"
        git config user.email "aaa@aaa.com"
        git add aaa.zip aaa.txt
        git commit -m "Upload zip"
        git push --atomic --force
