# Test 2024-05-05 at 00:21:45

name: Test

run-name: 2024-05-05 at 00:21:45

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/GithubCrud
        path: gh

    - name: Cpan
      run:  sudo cpan install -T Data::Dump  Digest::SHA1

    - name: Upload file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl -e"use v5.34; for(1..9999999) {say}" > aaa.txt
        zip aaa aaa.txt
        tree -h
        perl -Idtt/lib -Igh/lib -M"GitHub::Crud" -e"GitHub::Crud::writeBinaryFileFromFileInCurrentRun('aaa.txt', 'aaa.txt')"
        perl -Idtt/lib -Igh/lib -M"GitHub::Crud" -e"GitHub::Crud::writeBinaryFileFromFileInCurrentRun('aaa.zip', 'aaa.zip')"
